language: java
jdk: oraclejdk11
install: true
cache:
  directories:
    - $HOME/.m2

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 8cef3c5a-6697-4319-aa3d-573401603e2c